//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOT_Platform.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"@""[LOGIN]	   
[PASSWORD] 
[APP_ID]  	$id приложения $

[MCOUNT]    $максимальное количество сообщений, принимаемое ботом за раз$
[MTOFF]   	$максимальный период приянытх сообщений$

[PAUSE]     1000
[BNAME]     бот, Бот
[BMESMEM]   30

[ADMIN_LIST] """)]
        public string SettingsTemplateUserBot {
            get {
                return ((string)(this["SettingsTemplateUserBot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"@""[TOKEN]	   
[APP_ID]   	$id приложения $

[PAUSE]     1000
[MCOUNT]    50	  	$максимальное количество сообщений, принимаемое ботом за раз$
[MTOFF]     15		$максимальный период приянытх сообщений$

[BNAME]    бот,Бот
[BMESMEM]  30

[ADMIN_LIST] """)]
        public string SettingsTemplateGroupBot {
            get {
                return ((string)(this["SettingsTemplateGroupBot"]));
            }
        }
    }
}
